/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./pages/**/*.html",
    "./assets/js/**/*.js",
    "./components/**/*.js",
    "./components/**/*.html"
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        primary: {
          DEFAULT: '#0F766E',      // Deep teal — single brand accent
          dark: '#0C5D57',
          light: '#14B8A6',
          lighter: '#7DD3C8',
          lightest: '#D9F2EF',
          hover: '#0C5D57',
          50: '#F2FBF9',
          100: '#D9F2EF',
          200: '#B0E5DE',
          300: '#7DD3C8',
          400: '#3FB5A7',
          500: '#14998A',
          600: '#0F766E',
          700: '#0C5D57',
          800: '#0A4A45',
          900: '#0A3C38',
        },
        success: {
          DEFAULT: '#16A34A',
          light: '#E9F7EE',
          hover: '#15803D',
          50: '#F3FBF5',
          100: '#E9F7EE',
          500: '#16A34A',
          600: '#15803D',
          900: '#14532D',
        },
        warning: {
          DEFAULT: '#D97706',
          light: '#FCEFD8',
          hover: '#B45309',
          50: '#FDF8ED',
          100: '#FCEFD8',
          500: '#D97706',
          600: '#B45309',
          900: '#78350F',
        },
        danger: {
          DEFAULT: '#DC2626',
          light: '#FCE8E8',
          hover: '#B91C1C',
          50: '#FDF2F2',
          100: '#FCE8E8',
          500: '#EF4444',
          600: '#DC2626',
          700: '#B91C1C',
          900: '#7F1D1D',
        },
        info: {
          DEFAULT: '#0284C7',
          light: '#E3F1FA',
          hover: '#0369A1',
          50: '#F0F8FD',
          100: '#E3F1FA',
          500: '#0284C7',
          600: '#0369A1',
          900: '#0C4A6E',
        },
        // Text colors
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          disabled: 'var(--color-text-disabled)',
          light: '#F8FAFB',
          inverse: 'var(--color-text-inverse)',
        },
        // Surface/Background colors
        surface: {
          main: 'var(--color-surface-main)',
          card: 'var(--color-surface-card)',
          secondary: 'var(--color-surface-secondary)',
          hover: 'var(--color-surface-hover)',
          sidebar: 'var(--color-sidebar-bg)',
          'sidebar-hover': 'var(--color-sidebar-hover)',
          'sidebar-active': '#0F766E',
        },
        // Border colors
        border: {
          DEFAULT: 'var(--color-border)',
          light: 'var(--color-border-light)',
          dark: 'var(--color-border-dark)',
          focus: '#0F766E',
        },
        // Sidebar specific
        sidebar: {
          bg: 'var(--color-sidebar-bg)',
          hover: 'var(--color-sidebar-hover)',
          active: '#0F766E',
          text: 'var(--color-sidebar-text)',
          'text-muted': 'var(--color-sidebar-text-muted)',
        },
        // Chart colors
        chart: {
          primary: '#0F766E',
          secondary: '#14B8A6',
          tertiary: '#7DD3C8',
          grid: 'var(--color-border-light)',
        },
      },
      spacing: {
        'sidebar': '300px',
        'navbar': '70px',
      },
      zIndex: {
        'navbar': '1000',
        'dropdown': '1001',
        'hamburger': '1002',
        'modal': '2000',
        'alert': '3000',
        'loading': '3000',
        'overlay-alt': '9999',
        'toast': '10001',
      },
      // Decorative animations removed by design — only functional indicators remain.
      animation: {
        'spin-slow': 'spin 1s linear infinite',
        'toast-progress': 'toastProgress 4s linear forwards',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'bouncy': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      backdropBlur: {
        'xs': '1px',
        'sm': '2px',
        'md': '4px',
        'lg': '10px',
        'xl': '20px',
      },
      boxShadow: {
        'sm': '0 1px 2px rgba(16, 24, 40, 0.05)',
        'md': '0 2px 6px rgba(16, 24, 40, 0.06)',
        'lg': '0 8px 24px rgba(16, 24, 40, 0.08)',
        'xl': '0 16px 40px rgba(16, 24, 40, 0.12)',
        'card': '0 1px 2px rgba(16, 24, 40, 0.04)',
        'dropdown': '0 4px 16px rgba(16, 24, 40, 0.10)',
        'modal': '0 24px 56px rgba(16, 24, 40, 0.18)',
        'alert': '0 8px 24px rgba(16, 24, 40, 0.12)',
        'toast': '0 6px 20px rgba(16, 24, 40, 0.10)',
        'sidebar': '1px 0 0 rgba(16, 24, 40, 0.04)',
        'inset-sm': 'inset 0 1px 2px rgba(16, 24, 40, 0.06)',
        'focus': '0 0 0 3px rgba(15, 118, 110, 0.15)',
      },
      borderRadius: {
        DEFAULT: '6px',
        'lg': '10px',
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '1.5' }],
        'sm': ['13.5px', { lineHeight: '1.5' }],
        'base': ['14px', { lineHeight: '1.6' }],
        'lg': ['16px', { lineHeight: '1.6' }],
        'xl': ['19px', { lineHeight: '1.5' }],
        '2xl': ['23px', { lineHeight: '1.25' }],
        '3xl': ['30px', { lineHeight: '1.2' }],
        '4xl': ['38px', { lineHeight: '1.1' }],
      },
      gridTemplateColumns: {
        '10': 'repeat(10, minmax(0, 1fr))',
        'sidebar': '300px 1fr',
        'sidebar-collapsed': '70px 1fr',
      },
      gridAutoColumns: {
        'auto-fit': 'minmax(300px, 1fr)',
      },
    },
  },
  plugins: [],
}
